- name: Configure hosts resolver
  ansible.builtin.template:
    src: "{{ resolv_conf }}"
    dest: "{{ resolv_conf_dir }}/"

- name: Stop and disable hosts systemd-resolved service
  ansible.builtin.service:
    name: "{{ resolv_systemd_resolved_service_name }}"
    state: stopped
    enabled: no
