- name: Install Nginx package
  become: yes
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Configure Nginx enabled sites
  become: yes
  ansible.builtin.template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx service

- name: Start and enable Nginx service
  become: yes
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
