- name: Install Nginx service
  become: yes
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Add uWSGI configuration for Nginx service
  become: yes
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx service

- name: Start and enable Nginx service
  become: yes
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
