- name: Install Nginx
  become: yes
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Index page
  become: yes
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
