- name: Install Prometheus InfluxDB Stats Exporter
  ansible.builtin.get_url:
    url: "{{ influxdb_exporter_download_url }}"
    dest: "{{ influxdb_exporter_bin_path }}/{{ influxdb_exporter_bin }}"
    mode: 0755

- name: Configure Prometheus InfluxDB Stats Exporter service
  ansible.builtin.template:
    src: "{{ influxdb_exporter_service }}"
    dest: "{{ influxdb_exporter_service_path }}/{{ influxdb_exporter_service }}"
  notify:
    - Reload systemd daemon

- name: Start and enable Prometheus InfluxDB Stats Exporter service
  ansible.builtin.service:
    name: "{{ influxdb_exporter_service_name }}"
    state: started
    enabled: true
