- name: Install HAProxy packages
  ansible.builtin.apt:
    name: haproxy
    state: latest

- name: Copy HAProxy configuration
  ansible.builtin.template:
    src: "{{ haproxy_conf_name }}"
    dest: "{{ haproxy_config_root_dir }}/"
  notify:
    - Restart HAProxy service

- name: Enable and start HAProxy service
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true
