- name: Install HAProxy packages
  ansible.builtin.apt:
    name: "{{ haproxy_packages }}"
    state: latest

- name: Copy HAProxy configuration
  ansible.builtin.template:
    src: "{{ haproxy_conf }}"
    dest: "{{ haproxy_dir }}/"
  notify:
    - Restart HAProxy service

- name: Start and enable HAProxy service
  ansible.builtin.service:
    name: "{{ haproxy_service_name }}"
    state: started
    enabled: true
