- name: Install InfluxDB package
  ansible.builtin.apt:
    deb: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb

- name: Configure InfluxDB
  ansible.builtin.copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
  notify:
    - Restart InfluxDB service

- name: Add Telegraf APT key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/influxdb.gpg

- name: Add Telegraf APT repositories
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/debian stable main
    state: present
    filename: influxdata.list

- name: Install Telegraf and InfluxDB packages
  ansible.builtin.apt:
    name: telegraf
    state: present
    update_cache: yes

- name: Configure Telegraf
  ansible.builtin.template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify:
    - Restart Telegraf service

- name: Start and enable InfluxDB and Telegraf services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - telegraf
    - influxdb
