- name: Install InfluxDB packages
  ansible.builtin.apt:
    deb: "{{ item }}"
  with_items: "{{ influxdb_packages }}"

- name: Configure InfluxDB
  ansible.builtin.template:
    src: "{{ influxdb_conf }}"
    dest: "{{ influxdb_etc_dir }}/"
  notify:
    - Restart InfluxDB service

- name: Start and enable InfluxDB services
  ansible.builtin.service:
    name: "{{ influxdb_service_name }}"
    state: started
    enabled: true
