- name: Configure Rsyslog
  ansible.builtin.template:
    src: "{{ rsyslog_conf }}"
    dest: "{{ rsyslog_etc_dir }}/"
  notify:
    - Restart Rsyslog service

- name: Start and enable Rsyslog service
  ansible.builtin.service:
    name: "{{ rsyslog_service_name }}"
    state: started
    enabled: true
