- name: Configure Rsyslog
  ansible.builtin.template:
    src: 50-telegraf.conf
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify:
    - Restart Rsyslog service

- name: Start and enable Rsyslog service
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes
