- name: Create Grafana directories
  ansible.builtin.file:
    path: "{{ grafana_dirs }}"
    state: directory
    recurse: true

- name: Copy Grafana files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ grafana_files }}"
  notify:
    - Restart Grafana container

- name: Add Grafana templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ grafana_templates }}"
  notify:
    - Restart Grafana container

- name: Run Grafana Docker container
  community.docker.docker_container:
    name: "{{ grafana_docker_container_name }}"
    image: "{{ grafana_docker_image_name }}"
    volumes: "{{ grafana_dir }}:{{ grafana_docker_dir }}"
    published_ports: "{{ grafana_host_port }}:{{ grafana_docker_container_port }}"
  notify:
    - Restart Grafana container
