- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: latest

- name: Add Grafana APT key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repositories
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Install Grafana package
  ansible.builtin.apt:
    name: grafana
    state: latest
    update_cache: yes

- name: Configure Grafana service
  ansible.builtin.template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
  notify:
    - Restart Grafana service

- name: Start and enable Grafana service
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes

- name: Create datasources
  ansible.builtin.template:
    src: datasources.yml
    dest: /etc/grafana/provisioning/datasources/datasources.yml
  notify:
    - Restart Grafana service

- name: Provision Grafana dashboards
  ansible.builtin.copy:
    src: dashboards.yml
    dest: /etc/grafana/provisioning/dashboards/dashboards.yml
  notify:
    - Restart Grafana service

- name: Ensure Grafana dashboards directory exists
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: Import Grafana dashboards
  ansible.builtin.copy:
    src: "{{ item }}.json"
    dest: /var/lib/grafana/dashboards/{{ item }}.json
  with_items:
    - main
    - syslog
  notify:
    - Restart Grafana service
