- name: Create Grafana directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop: "{{ grafana_dirs }}"

- name: Copy Grafana resources
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ grafana_resources }}"
  notify:
    - Restart Grafana Docker container

- name: Copy Grafana configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ grafana_configs }}"
  notify:
    - Restart Grafana Docker container

- name: Run Grafana Docker container
  community.docker.docker_container:
    name: "{{ grafana_docker_container_name }}"
    image: "{{ grafana_docker_container_image }}"
    volumes: "{{ grafana_config_root_dir }}:{{ grafana_container_config_root_dir }}"
    published_ports: "{{ grafana_service_port }}:{{ grafana_container_port }}"
  notify:
    - Restart Grafana Docker container
