- name: Initialize hosts
  hosts: all
  roles:
    - setup
    - init
    - backup

- name: Deploy DNS servers
  hosts: dns_servers
  roles:
    - bind
    - bind_exporter

- name: Configure hosts
  hosts: all
  roles:
    - resolv
    - node_exporter
    - rsyslog

- name: Deploy Nginx servers
  hosts: nginx_servers
  roles:
    - nginx
    - nginx_exporter

- name: Deploy database servers
  hosts: db_servers
  roles:
    - mysql
    - mysql_backup
    - mysql_exporter

- name: Deploy Docker hosts
  hosts: docker_hosts
  roles:
    - docker

- name: Deploy HAProxy hosts
  hosts: haproxy_servers
  roles:
    - keepalived
    - keepalived_exporter
    - haproxy
    - haproxy_exporter

- name: Deploy web servers
  hosts: web_servers
  roles:
    - agama

- name: Deploy monitoring servers
  hosts: monitoring_servers
  roles:
    - prometheus
    - grafana
    - influxdb
    - telegraf
    - influxdb_backup
    - pinger
    - influxdb_exporter
