- name: Initialize hosts
  hosts: all
  roles:
    - setup
    - init
    - resolv

- name: Deploy DNS servers
  hosts: dns_servers
  roles:
    - bind

- name: Deploy database servers
  hosts: db_servers
  roles:
    - mysql

- name: Deploy web servers
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
