- name: Initialize hosts
  hosts: all
  roles:
    - setup
    - init

- name: Deploy DNS servers
  hosts: dns_servers
  roles:
    - bind

- name: Configure hosts
  hosts: all
  roles:
    - resolv
    - node_exporter

- name: Deploy database servers
  hosts: db_servers
  roles:
    - mysql

- name: Deploy web servers
  hosts: web_servers
  roles:
    - uwsgi
    - agama

- name: Deploy monitoring server
  hosts: monitoring_servers
  roles:
    - prometheus
