- name: Restore InfluxDB database
  hosts: monitoring_servers
  tasks:

    - name: Clear InfluxDB backup restore directory
      ansible.builtin.file:
        path: "{{ influxdb_backup_restore_dir }}"
        state: absent

    - name: Download InfluxDB database backup
      ansible.builtin.shell: |
        sudo -u {{ backup_user_username }} duplicity --no-encryption restore \
          rsync://{{ backup_host_user_username }}@{{ backup_host_fqdn }}/{{ influxdb_backup_host_dir }} \
          {{ influxdb_backup_restore_dir }}

    - name: Stop Telegraf service
      ansible.builtin.service:
        name: "{{ telegraf_service_name }}"
        state: stopped

    - name: Restore InfluxDB database
      ansible.builtin.shell: |
        influx -execute 'DROP DATABASE {{ telegraf_influxdb_db_name }}'
        influxd restore -portable -database {{ telegraf_influxdb_db_name }} {{ influxdb_backup_restore_dir }}
      ignore_errors: true

    - name: Stop Telegraf service
      ansible.builtin.service:
        name: "{{ telegraf_service_name }}"
        state: started
