- name: Restore MySQL database
  hosts: db_servers
  tasks:
    - name: Download MySQL database backup
      ansible.builtin.shell: |
        rm -rf {{ backup_user_home_restore_mysql }}/*
        sudo -u {{ backup_user }} duplicity --no-encryption restore \
          rsync://{{ backup_host_user }}@{{ backup_host_fqdn }}/mysql \
          {{ backup_user_home_restore_mysql }}

    - name: Grant executable permissions to backup script
      ansible.builtin.file:
        path: "{{ backup_user_home_restore_mysql }}/{{ mysql_db }}.sql"
        mode: 0660

    - name: Restore MySQL database
      ansible.builtin.shell: mysql {{ mysql_db }} < {{ backup_user_home_restore_mysql }}/{{ mysql_db }}.sql
