{
 "title": "MySQL",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "MySQL Selects Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "irate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL Server Read-Only Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL Slave SQL Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL Server IDs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "MySQL Slave IO Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}