- name: Restart BIND 9 service
  become: yes
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: Reload BIND 9 configuration
  become: yes
  ansible.builtin.shell:
    cmd: rndc reload
