- name: Create AGAMA directory
  ansible.builtin.file:
    path: "{{ agama_dir }}"
    state: directory
    recurse: true

- name: Download AGAMA files
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ agama_dir }}/"
  loop: "{{ agama_urls }}"
  notify:
    - Restart AGAMA Docker container

- name: Build AGAMA Docker image
  community.docker.docker_image:
    name: "{{ agama_docker_image_name }}"
    source: build
    build:
      path: "{{ agama_dir }}"
  notify:
    - Restart AGAMA Docker container

- name: Run AGAMA Docker container
  community.docker.docker_container:
    name: "{{ agama_docker_container_name }}"
    image: "{{ agama_docker_image_name }}"
    published_ports: "{{ agama_host_port }}:{{ agama_container_port }}"
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_agama_user }}:{{ mysql_agama_password }}@{{ mysql_host }}/{{ mysql_agama_db }}
  notify:
    - Restart AGAMA Docker container
