- name: Create AGAMA directory
  ansible.builtin.file:
    path: "{{ agama_dir }}"
    state: directory
    recurse: true

- name: Download AGAMA files
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ agama_dir }}/"
  with_items: "{{ agama_file_urls }}"
  notify:
    - Restart AGAMA container

- name: Build AGAMA image
  community.docker.docker_image:
    name: "{{ agama_docker_image_name }}"
    source: build
    build:
      path: "{{ agama_dir }}"
  notify:
    - Restart AGAMA container

- name: Run AGAMA container
  community.docker.docker_container:
    name: "{{ agama_docker_container_name }}"
    image: "{{ agama_docker_image_name }}"
    published_ports: "{{ agama_host_port }}:{{ agama_docker_container_port }}"
    restart_policy: always
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_agama_user_username }}:{{ mysql_agama_user_password }}@{{ mysql_master_host }}/{{ mysql_agama_db_name }}
  notify:
    - Restart AGAMA container
