- name: Create backup user
  ansible.builtin.user:
    name: backup
    state: present
    create_home: yes
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa

- name: Add backup server SSH key to known hosts list
  ansible.builtin.known_hosts:
    name: backup.{{ domain }}
    key: backup,backup.{{ domain }},{{ backup_server_ip }} {{ backup_server_ssh_key }}
    path: /home/backup/.ssh/known_hosts
    state: present
