- name: Create backup user
  ansible.builtin.user:
    name: "{{ backup_user_username }}"
    state: present
    create_home: true
    home: "{{ backup_user_home }}"
    generate_ssh_key: true
    ssh_key_file: .ssh/id_rsa

- name: Add backup server SSH key to known hosts list
  ansible.builtin.known_hosts:
    name: "{{ backup_host_fqdn }}"
    key: "{{ backup_host_ipaddr }},{{ backup_host_fqdn }},{{ backup_host_ipaddr }} {{ backup_host_ssh_key }}"
    path: "{{ backup_user_home }}/.ssh/known_hosts"
    state: present

- name: Create restore directory
  ansible.builtin.file:
    path: "{{ backup_user_home_restore }}"
    state: directory
    owner: "{{ backup_user_username }}"

- name: Install Duplicity package
  ansible.builtin.apt:
    name: duplicity
    state: present
