- name: Install Prometheus MySQL Exporter package
  ansible.builtin.apt:
    name: "{{ mysql_exporter_packages }}"
    state: latest

- name: Create MySQL user for Prometheus MySQL Exporter
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user_username }}"
    password: "{{ mysql_exporter_user_password }}"
    host: "%"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    resource_limits:
      MAX_USER_CONNECTIONS: 3
    login_unix_socket: "{{ mysql_socket }}"

- name: Configure MySQL client for Prometheus MySQL Exporter
  ansible.builtin.template:
    src: "{{ mysql_exporter_client_conf }}"
    dest: "{{ mysql_exporter_client_conf_path }}/{{ mysql_exporter_client_conf }}"
    mode: 0600
    owner: "{{ mysql_exporter_user_username }}"
  notify:
    - Restart Prometheus MySQL Exporter service

- name: Configure Prometheus MySQL Exporter service
  ansible.builtin.template:
    src: "{{ mysql_exporter_conf }}"
    dest: "{{ mysql_exporter_conf_dir }}/"
  notify:
    - Restart Prometheus MySQL Exporter service

- name: Start and enable Prometheus MySQL Exporter service
  ansible.builtin.service:
    name: "{{ mysql_exporter_service_name }}"
    state: started
    enabled: true
  retries: 5
  delay: 10
