- name: Install Prometheus MySQL Exporter package
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
    state: latest

- name: Create MySQL user for Prometheus MySQL Exporter
  community.mysql.mysql_user:
    name: "{{ prometheus_user }}"
    password: "{{ mysql_exporter_password }}"
    host: "%"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    resource_limits:
      MAX_USER_CONNECTIONS: 3
    login_unix_socket: "{{ mysql_socket }}"

- name: Configure MySQL client for Prometheus MySQL Exporter
  ansible.builtin.template:
    src: .mysqld_exporter.cnf
    dest: /etc/.mysqld_exporter.cnf
    mode: 0600
    owner: "{{ prometheus_user }}"
  notify:
    - Restart Prometheus MySQL Exporter service

- name: Expose Prometheus MySQL Exporter service
  ansible.builtin.template:
    src: prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter
  notify:
    - Restart Prometheus MySQL Exporter service

- name: Start and enable Prometheus MySQL Exporter service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
