- name: Install MySQL packages
  become: yes
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
    state: latest

- name: Start and enable MySQL service
  become: yes
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Configure MySQL service
  become: yes
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
    - Restart MySQL service

- name: Create MySQL database
  become: yes
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user
  become: yes
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
