- name: Install MySQL packages
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
    state: latest

- name: Start and enable MySQL service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Configure MySQL daemon
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
    - Restart MySQL service

- name: Create MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_db }}"
    login_unix_socket: "{{ mysql_socket }}"

- name: Create MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_db }}.*:ALL"
    login_unix_socket: "{{ mysql_socket }}"
  notify:
    - Restart MySQL service
