apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost/prometheus
    isDefault: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    database: telegraf
    url: http://localhost:{{ influxdb_port }}
    jsonData:
      httpMode: GET
