apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus/prometheus
    isDefault: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    database: "{{ telegraf_influxdb_db_name }}"
    url: http://influxdb:{{ influxdb_host_port }}
    jsonData:
      httpMode: GET
