- name: Install Prometheus Node Exporter package
  ansible.builtin.apt:
    name: "{{ node_exporter_packages }}"
    state: latest

- name: Start and enable Prometheus Node Exporter service
  ansible.builtin.service:
    name: "{{ node_exporter_service_name }}"
    state: started
    enabled: true
