- name: Create required users
  become: yes
  ansible.builtin.user:
    name: "{{ item.login }}"
    create_home: yes
    groups: sudo
    state: present
  with_items:
    - "{{ users }}"

- name: Add required users SSH pubkeys
  become: yes
  ansible.posix.authorized_key:
    user: "{{ item.login }}"
    key: "{{ item.pubkey }}"
    state: present
  with_items:
    - "{{ users }}"
