- name: Create required users
  ansible.builtin.user:
    name: "{{ item.login }}"
    create_home: true
    groups: sudo
    state: present
  with_items: "{{ users }}"

- name: Add required users SSH pubkeys
  ansible.posix.authorized_key:
    user: "{{ item.login }}"
    key: "{{ item.pubkey }}"
    state: present
  with_items: "{{ users }}"
