- name: Create Pinger user
  ansible.builtin.user:
    name: "{{ pinger_user_username }}"
    state: present
    system: true

- name: Install Pinger packages
  ansible.builtin.apt:
    name: "{{ pinger_packages }}"
    state: latest

- name: Install Pinger binary
  ansible.builtin.template:
    src: "{{ pinger_shell }}"
    dest: "{{ pinger_shell_dir }}/"
    mode: 0755

- name: Configure Pinger service
  ansible.builtin.template:
    src: "{{ pinger_service }}"
    dest: "{{ pinger_service_path }}/"
  notify:
    - Reload systemd daemon

- name: Create Pinger directory
  ansible.builtin.file:
    path: "{{ pinger_etc_dir }}"
    state: directory

- name: Configure Pinger
  ansible.builtin.template:
    src: "{{ pinger_conf }}"
    dest: "{{ pinger_etc_dir }}/{{ pinger_conf }}"
  notify:
    - Restart Pinger service

- name: Start and enable Pinger service
  ansible.builtin.service:
    name: "{{ pinger_service_name }}"
    state: started
    enabled: true
