- name: Install Prometheus BIND Exporter packages
  ansible.builtin.apt:
    name: "{{ bind_exporter_packages }}"
    state: latest

- name: Configure Prometheus BIND Exporter service
  ansible.builtin.template:
    src: "{{ bind_exporter_conf }}"
    dest: "{{ bind_exporter_conf_dir }}"
  notify:
    - Restart Prometheus BIND Exporter service

- name: Start and enable Prometheus BIND Exporter service
  ansible.builtin.service:
    name: "{{ bind_exporter_service_name }}"
    state: started
    enabled: true
