- name: Install Prometheus BIND Exporter package
  ansible.builtin.apt:
    name: prometheus-bind-exporter
    state: latest

- name: Expose Prometheus BIND Exporter service
  ansible.builtin.template:
    src: prometheus-bind-exporter
    dest: /etc/default/prometheus-bind-exporter
  notify:
    - Restart Prometheus BIND Exporter service

- name: Start and enable Prometheus BIND Exporter service
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: started
    enabled: true
