- name: Restart InfluxDB service
  ansible.builtin.service:
    name: influxdb
    state: restarted


- name: Restart Telegraf service
  ansible.builtin.service:
    name: telegraf
    state: restarted
