- name: Install Keepalived packages
  ansible.builtin.apt:
    name: keepalived

- name: Create keepalived user
  ansible.builtin.user:
    name: "{{ keepalived_user }}"

- name: Copy Keepalived configuration
  ansible.builtin.template:
    src: "{{ keepalived_conf_name }}"
    dest: "{{ keepalived_config_root_dir }}/"
  notify:
    - Restart Keepalived service

- name: Copy Keepalived healthcheck script
  ansible.builtin.copy:
    src: "{{ keepalived_healthcheck_script_name }}"
    dest: "{{ keepalived_script_user_home_dir }}/"
    owner: "{{ keepalived_user }}"
    group: "{{ keepalived_user }}"
    mode: 0700
  notify:
    - Restart Keepalived service

- name: Enable and start Keepalived service
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: yes