- name: Install Keepalived packages
  ansible.builtin.apt:
    name: "{{ keepalived_packages }}"

- name: Create Keepalived user
  ansible.builtin.user:
    name: "{{ keepalived_user_username }}"

- name: Configure Keepalived service
  ansible.builtin.template:
    src: "{{ keepalived_conf }}"
    dest: "{{ keepalived_etc_dir }}/"
  notify:
    - Restart Keepalived service

- name: Add Keepalived healthcheck script
  ansible.builtin.template:
    src: "{{ keepalived_healthcheck_script }}"
    dest: "{{ keepalived_user_home }}/"
    owner: "{{ keepalived_user_username }}"
    group: "{{ keepalived_group_name }}"
    mode: 0700
  notify:
    - Restart Keepalived service

- name: Start and enable Keepalived service
  ansible.builtin.service:
    name: "{{ keepalived_service_name }}"
    state: started
    enabled: true
