- name: Download Prometheus Keepalived Exporter binary
  ansible.builtin.get_url:
    url: "{{ keepalived_exporter_download_url }}"
    dest: "{{ keepalived_exporter_download_tar_path }}"

- name: Extract Prometheus Keepalived Exporter binary
  ansible.builtin.unarchive:
    src: "{{ keepalived_exporter_download_tar_path }}/{{ keepalived_exporter_download_tar }}"
    dest: "{{ keepalived_exporter_download_tar_path }}/"
    remote_src: true

- name: Copy Prometheus Keepalived Exporter binary to binary directory
  ansible.builtin.copy:
    src: "{{ keepalived_exporter_download_tar_path }}/{{ keepalived_exporter_download_dir }}/{{ keepalived_exporter_download_file }}"
    dest: "{{ keepalived_exporter_bin_path }}/{{ keepalived_exporter_bin }}"
    mode: 0755
    remote_src: true

- name: Copy Prometheus Keepalived Exporter service
  ansible.builtin.template:
    src: "{{ keepalived_exporter_service }}"
    dest: "{{ keepalived_exporter_service_path }}/"
  notify:
    - Reload systemd daemon

- name: Start and enable Prometheus Keepalived Exporter service
  ansible.builtin.service:
    name: "{{ keepalived_exporter_service_name }}"
    state: started
    enabled: true
