- name: Install Prometheus HAProxy Exporter packages
  ansible.builtin.apt:
    name: "{{ haproxy_exporter_packages }}"
    state: latest

- name: Configure Prometheus HAProxy Exporter service
  ansible.builtin.template:
    src: "{{ haproxy_exporter_conf }}"
    dest: "{{ haproxy_exporter_conf_dir }}"
  notify:
    - Restart Prometheus HAProxy Exporter service

- name: Start and enable Prometheus HAProxy Exporter service
  ansible.builtin.service:
    name: "{{ haproxy_exporter_service_name }}"
    state: started
    enabled: true
