- name: Install Prometheus package
  ansible.builtin.apt:
    name: prometheus
    state: latest

- name: Configure Prometheus service
  ansible.builtin.template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Restart Prometheus service

- name: Expose Prometheus service
  ansible.builtin.template:
    src: prometheus
    dest: /etc/default/prometheus
  notify:
    - Restart Prometheus service

- name: Enable and start Prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
