- name: Install Prometheus Nginx Exporter package
  ansible.builtin.apt:
    name: "{{ nginx_exporter_packages }}"
    state: latest

- name: Expose Prometheus Nginx Exporter service
  ansible.builtin.template:
    src: "{{ nginx_exporter_conf }}"
    dest: "{{ nginx_exporter_conf_dir }}/{{ nginx_exporter_conf }}"
  notify:
    - Restart Prometheus Nginx Exporter service

- name: Start and enable Prometheus Nginx Exporter service
  ansible.builtin.service:
    name: "{{ nginx_exporter_service_name }}"
    state: started
    enabled: true
