- name: Install Prometheus Nginx Exporter package
  ansible.builtin.apt:
    name: prometheus-nginx-exporter
    state: latest

- name: Expose Prometheus Nginx Exporter service
  ansible.builtin.template:
    src: prometheus-nginx-exporter
    dest: /etc/default/prometheus-nginx-exporter
  notify:
    - Restart Prometheus Nginx Exporter service

- name: Start and enable Prometheus Nginx Exporter service
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true
