- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: latest

- name: Start and enable Docker service
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: true
