- name: Install Docker required package
  ansible.builtin.apt:
    name:
     - docker.io
     - python3-docker

- name: Start and enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
