- name: Install BIND 9 package
  ansible.builtin.apt:
    name: bind9
    state: latest

- name: Start and enable BIND 9 service
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes

- name: Configure BIND 9 service
  ansible.builtin.template:
    src: named.conf
    dest: /etc/bind/named.conf
  notify:
    - Restart BIND 9 service

- name: Configure BIND 9 master zone
  ansible.builtin.template:
    src: db.{{ domain }}
    dest: /var/lib/bind/db.{{ domain }}
  notify:
    - Reload BIND 9 configuration
