- name: Install BIND 9 packages
  ansible.builtin.apt:
    name: "{{ bind_packages }}"
    state: latest

- name: Configure BIND 9 service
  ansible.builtin.template:
    src: "{{ bind_named_conf }}"
    dest: "{{ bind_etc_dir }}/"
  notify:
    - Restart BIND 9 service

- name: Initialize BIND 9 zones
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ bind_var_dir }}/"
    force: false
  with_items: "{{ bind_zone_files }}"
  notify:
    - Reload BIND 9 configuration

- name: Add BIND 9 keys
  ansible.builtin.template:
    src: "{{ bind_named_conf_options }}"
    dest: "{{ bind_etc_dir }}/"
  notify:
    - Reload BIND 9 configuration

- name: Start and enable BIND 9 service
  ansible.builtin.service:
    name: "{{ bind_service_name }}"
    state: started
    enabled: true

- name: Add BIND 9 main zone records
  community.general.nsupdate:
    key_name: "{{ bind_nsupdate_key_name }}"
    key_algorithm: "{{ bind_key_algorithm }}"
    key_secret: "{{ bind_nsupdate_key_secret }}"
    server: "{{ groups['dns_masters'][0] }}"
    zone: "{{ bind_main_zone }}"
    record: "{{ item.record }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
  with_items: "{{ bind_main_zone_records }}"
  when: inventory_hostname == groups['dns_masters'][0]

- name: Add BIND 9 reverse zone records
  community.general.nsupdate:
    key_name: "{{ bind_nsupdate_key_name }}"
    key_algorithm: "{{ bind_key_algorithm }}"
    key_secret: "{{ bind_nsupdate_key_secret }}"
    server: "{{ groups['dns_masters'][0] }}"
    zone: "{{ bind_reverse_zone }}"
    record: "{{ item.record }}"
    value: "{{ item.value }}.{{ bind_main_zone }}."
    type: PTR
  with_items: "{{ bind_reverse_zone_records }}"
  when: inventory_hostname == groups['dns_masters'][0]
