- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: "{{ init_cache_valid_time }}"

- name: Install init packages
  ansible.builtin.apt:
    name: "{{ init_packages }}"
    state: latest
